
#set(ESP_IDF_PATH "/CH/development/sdk/esp-idf") #old absolute path to sdk location
set(ESP_IDF_PATH "${PROJECT_SOURCE_DIR}/components/esp-idf") #new sdk location will be managed as a git submodule in components directory.

#Includes for ESP IDF sdk toolchain
include_directories("${ESP_IDF_PATH}")
include_directories("${ESP_IDF_PATH}/components/app_trace/include")
include_directories("${ESP_IDF_PATH}/components/app_trace/sys_view/Config")
include_directories("${ESP_IDF_PATH}/components/app_trace/sys_view/SEGGER")
include_directories("${ESP_IDF_PATH}/components/app_update/include")
include_directories("${ESP_IDF_PATH}/components/aws_iot/include")
include_directories("${ESP_IDF_PATH}/components/bootloader/subproject/main")
include_directories("${ESP_IDF_PATH}/components/bootloader_support/include")
include_directories("${ESP_IDF_PATH}/components/bootloader_support/include_priv")

include_directories("${ESP_IDF_PATH}/components/bt/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/include")
#Not sure if bt includes are necessary, but helps with indexing
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/api/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/ar")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/av")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/dm")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/gatt")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/hh")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/sdp")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/bta/sys/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/esp/blufi/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/esp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/a2dp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/avrc/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/battery/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/dis/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/hid/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/sdp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btc/profile/std/smp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/btcore/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/device/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/external/sbc/decoder/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/external/sbc/encoder/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/hci/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/osi/include")

include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/a2dp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/avct/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/avdt/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/avrc/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/btm/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/btu/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/gap/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/gatt/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/hcic/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/include/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/l2cap/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/rfcomm/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/sdp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/stack/smp/include")
include_directories("${ESP_IDF_PATH}/components/bt/bluedroid/utils/include")


include_directories("${ESP_IDF_PATH}/components/coap/port/include")
include_directories("${ESP_IDF_PATH}/components/coap/port/include/coap")
#include_directories("${ESP_IDF_PATH}/components/coap/libcoap/include")
#include_directories("${ESP_IDF_PATH}/components/coap/libcoap/include/coap")

include_directories("${ESP_IDF_PATH}/components/console")
include_directories("${ESP_IDF_PATH}/components/console/argtable3")
include_directories("${ESP_IDF_PATH}/components/console/linenoise")
#include_directories("${ESP_IDF_PATH}/components/cxx/include")
include_directories("${ESP_IDF_PATH}/components/driver")
include_directories("${ESP_IDF_PATH}/components/driver/include")
include_directories("${ESP_IDF_PATH}/components/driver/include/driver")
include_directories("${ESP_IDF_PATH}/components/esp32")
include_directories("${ESP_IDF_PATH}/components/esp32/include")
include_directories("${ESP_IDF_PATH}/components/esp32/include/esp32")
include_directories("${ESP_IDF_PATH}/components/esp32/include/hwcrypto")
include_directories("${ESP_IDF_PATH}/components/esp32/include/rom")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/config")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/tie")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/xtav60/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/xtav110/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/xtav200/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/xtkc705/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp32/include/xtensa/xtml605/xtensa")
include_directories("${ESP_IDF_PATH}/components/esp_adc_cal/include")
include_directories("${ESP_IDF_PATH}/components/ethernet")
include_directories("${ESP_IDF_PATH}/components/ethernet/include")
include_directories("${ESP_IDF_PATH}/components/expat/include/expat")
include_directories("${ESP_IDF_PATH}/components/expat/port/include")
include_directories("${ESP_IDF_PATH}/components/fatfs/src")
include_directories("${ESP_IDF_PATH}/components/fatfs/test")
include_directories("${ESP_IDF_PATH}/components/freertos")
include_directories("${ESP_IDF_PATH}/components/freertos/include")
include_directories("${ESP_IDF_PATH}/components/heap")
include_directories("${ESP_IDF_PATH}/components/heap/include")
include_directories("${ESP_IDF_PATH}/components/idf_test/include")
include_directories("${ESP_IDF_PATH}/components/jsmn/include")
include_directories("${ESP_IDF_PATH}/components/json/include")
include_directories("${ESP_IDF_PATH}/components/json/port/include")
include_directories("${ESP_IDF_PATH}/components/libsodium/port")
include_directories("${ESP_IDF_PATH}/components/libsodium/port_include/sodium")
include_directories("${ESP_IDF_PATH}/components/log/include")


include_directories("${ESP_IDF_PATH}/components/lwip/apps/ping")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/apps")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/apps/sntp")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/lwip")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/lwip/priv")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/netif")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/netif/ppp")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/netif/ppp/polarssl")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/port")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/port/arch")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/port/arpa")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/port/netif")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/port/netinet")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/posix")
include_directories("${ESP_IDF_PATH}/components/lwip/include/lwip/posix/sys")

include_directories("${ESP_IDF_PATH}/components/mbedtls/port/include")
include_directories("${ESP_IDF_PATH}/components/mbedtls/include/mbedtls")
include_directories("${ESP_IDF_PATH}/components/mdns/include")
include_directories("${ESP_IDF_PATH}/components/mdns/test_afl_fuzz_host")

#include_directories("${ESP_IDF_PATH}/components/micro-ecc/micro-ecc")
include_directories("${ESP_IDF_PATH}/components/newlib/include")
include_directories("${ESP_IDF_PATH}/components/newlib/include/machine")
include_directories("${ESP_IDF_PATH}/components/newlib/include/sys")
include_directories("${ESP_IDF_PATH}/components/newlib/include/xtensa/config")
include_directories("${ESP_IDF_PATH}/components/newlib/platform_include")
#include_directories("${ESP_IDF_PATH}/components/nghttp/include")
include_directories("${ESP_IDF_PATH}/components/nghttp/port/include")
include_directories("${ESP_IDF_PATH}/components/nghttp/port/include/nghttp2ver")
include_directories("${ESP_IDF_PATH}/components/nvs_flash/include")
include_directories("${ESP_IDF_PATH}/components/openssl/include")
include_directories("${ESP_IDF_PATH}/components/openssl/include/internal")
include_directories("${ESP_IDF_PATH}/components/openssl/include/platform")
include_directories("${ESP_IDF_PATH}/components/openssl/include/openssl")

include_directories("${ESP_IDF_PATH}/components/soc/include/soc")
include_directories("${ESP_IDF_PATH}/components/soc/esp32")
include_directories("${ESP_IDF_PATH}/components/soc/esp32/include/soc")

include_directories("${ESP_IDF_PATH}/components/spi_flash")
include_directories("${ESP_IDF_PATH}/components/spi_flash/include")
include_directories("${ESP_IDF_PATH}/components/spiffs/include")
include_directories("${ESP_IDF_PATH}/components/tcpip_adapter/include")
include_directories("${ESP_IDF_PATH}/components/ulp/include")
include_directories("${ESP_IDF_PATH}/components/vfs/include")
include_directories("${ESP_IDF_PATH}/components/vfs/include/sys")
include_directories("${ESP_IDF_PATH}/components/wear_levelling")
include_directories("${ESP_IDF_PATH}/components/wear_levelling/include")
include_directories("${ESP_IDF_PATH}/components/wear_levelling/test_wl_host")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/include/crypto")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/include/wpa")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/include/wpa2/eap_peer")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/include/wpa2/tls")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/include/wpa2/utils")
include_directories("${ESP_IDF_PATH}/components/wpa_supplicant/port/include")
include_directories("${ESP_IDF_PATH}/components/xtensa-debug-module/include")
