
set(ESP_ARDUINO_PATH "/CH/development/sdk/arduino-esp32")

#Includes files for Arduino-ESP
include_directories("${ESP_ARDUINO_PATH}")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/config")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/bluedroid")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/app_update")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/bootloader_support")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/bt")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/driver")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/esp32")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/ethernet")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/fatfs")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/freertos")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/jsmn")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/log")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/mdns")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/mbedtls")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/mbedtls_port")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/newlib")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/nvs_flash")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/openssl")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/soc")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/spi_flash")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/sdmmc")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/tcpip_adapter")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/ulp")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/vfs")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/wear_levelling")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/xtensa-debug-module")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/newlib")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/coap")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/wpa_supplicant")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/expat")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/json")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/nghttp")
include_directories("${ESP_ARDUINO_PATH}/tools/sdk/include/lwip")
include_directories("${ESP_ARDUINO_PATH}/cores/esp32")
include_directories("${ESP_ARDUINO_PATH}/variants/esp32thing")
include_directories("${ESP_ARDUINO_PATH}/libraries/ArduinoOTA/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/ESP32/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/ESPmDNS/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/FS/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/Preferences/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/SD/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/SD_MMC/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/SPI/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/SimpleBLE/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/Update/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/WiFi/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/WiFiClientSecure/src")
include_directories("${ESP_ARDUINO_PATH}/libraries/Wire/src")


